In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
 

In [2]:
train_data = pd.read_csv('data/yancheng_train.csv')
train_data.columns

E:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (15,20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Index(['sale_date', 'class_id', 'sale_quantity', 'brand_id', 'compartment',
       'type_id', 'level_id', 'department_id', 'TR', 'gearbox_type',
       'displacement', 'if_charging', 'price_level', 'price', 'driven_type_id',
       'fuel_type_id', 'newenergy_type_id', 'emission_standards_id',
       'if_MPV_id', 'if_luxurious_id', 'power', 'cylinder_number',
       'engine_torque', 'car_length', 'car_width', 'car_height',
       'total_quality', 'equipment_quality', 'rated_passenger', 'wheelbase',
       'front_track', 'rear_track'],
      dtype='object')

In [7]:
# class_ids = np.unique(train_data['class_id'])
sale_quantity_perclass = train_data[['sale_date','class_id','sale_quantity']]\
                            .groupby(by=['sale_date','class_id'],as_index=False).sum()

In [10]:
np.unique(sale_quantity_perclass['sale_date'],return_counts=True)

(array([201201, 201202, 201203, 201204, 201205, 201206, 201207, 201208,
        201209, 201210, 201211, 201212, 201301, 201302, 201303, 201304,
        201305, 201306, 201307, 201308, 201309, 201310, 201311, 201312,
        201401, 201402, 201403, 201404, 201405, 201406, 201407, 201408,
        201409, 201410, 201411, 201412, 201501, 201502, 201503, 201504,
        201505, 201506, 201507, 201508, 201509, 201510, 201511, 201512,
        201601, 201602, 201603, 201604, 201605, 201606, 201607, 201608,
        201609, 201610, 201611, 201612, 201701, 201702, 201703, 201704,
        201705, 201706, 201707, 201708, 201709, 201710], dtype=int64),
 array([ 42,  43,  44,  45,  46,  44,  46,  45,  47,  48,  49,  51,  51,
         50,  52,  53,  55,  55,  56,  57,  59,  59,  61,  60,  62,  62,
         61,  61,  63,  65,  66,  69,  71,  73,  74,  75,  78,  79,  80,
         80,  82,  83,  86,  87,  89,  89,  90,  91,  92,  94,  98, 100,
        100, 103, 105, 105, 109, 112, 118, 118, 120, 121, 125

In [13]:
classes, class_sale_counts = np.unique(sale_quantity_perclass['class_id'],return_counts=True)

In [14]:
classes_most_recorded = classes[class_sale_counts>=70]
classes_most_recorded

array([125403, 136916, 178529, 209945, 248352, 281301, 290854, 291086,
       304458, 321683, 349023, 354068, 379876, 384924, 409854, 425432,
       468392, 472603, 482497, 527809, 559132, 576298, 580470, 597927,
       603972, 614059, 628041, 651347, 682651, 713651, 714152, 735971,
       819061, 883691, 914348, 961362, 961962], dtype=int64)

In [17]:
figure = plt.figure()
for id in classes_most_recorded:
    tp = sale_quantity_perclass[sale_quantity_perclass.class_id == id]
    plt.plot(tp.sale_quantity)
plt.show()
    