In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdate


In [65]:
# parser = lambda date: pd.datetime.strptime(date, '%Y%m')
train_data = pd.read_csv('data/yancheng_train.csv',na_values=['-'])
train_data.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20157 entries, 0 to 20156
Data columns (total 32 columns):
sale_date                20157 non-null int64
class_id                 20157 non-null int64
sale_quantity            20157 non-null int64
brand_id                 20157 non-null int64
compartment              20157 non-null int64
type_id                  20157 non-null int64
level_id                 19859 non-null float64
department_id            20157 non-null int64
TR                       20157 non-null object
gearbox_type             20157 non-null object
displacement             20157 non-null float64
if_charging              20157 non-null object
price_level              20157 non-null object
price                    11377 non-null float64
driven_type_id           20157 non-null int64
fuel_type_id             20154 non-null float64
newenergy_type_id        20157 non-null int64
emission_standards_id    20157 non-null int64
if_MPV_id                20157 non-null int64
if_lu

E:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [86]:
train_data[train_data.fuel_type_id != train_data.fuel_type_id]


(array([201201, 201202, 201203, 201204, 201205, 201206, 201207, 201208,
       201209, 201210, 201211, 201212, 201301, 201302, 201303, 201304,
       201305, 201306, 201307, 201308, 201309, 201310, 201311, 201312,
       201401, 201402, 201403, 201404, 201405, 201406, 201407, 201408,
       201409, 201410, 201411, 201412, 201501, 201502, 201503, 201504,
       201505, 201506, 201507, 201508, 201509, 201510, 201511, 201512,
       201601, 201602, 201603, 201604, 201605, 201606, 201607, 201608,
       201609, 201610, 201611, 201612, 201701, 201702, 201703, 201704,
       201705, 201706, 201707, 201708, 201709, 201710], dtype=int64), array([171, 153, 168, 156, 166, 159, 176, 172, 187, 183, 184, 183, 213,
       188, 178, 192, 193, 195, 211, 218, 225, 235, 235, 221, 260, 230,
       240, 256, 278, 267, 301, 299, 348, 342, 330, 347,  22,  23,  27,
        22,  21,  18,  21,  26,  24,  25,  24,  28,  30,  31,  29,  22,
        17,  17,  16,  18,  18,  17,  14,  14,  17,  18,  19,  17,  19,
 

In [82]:
print(np.unique(train_data[train_data.level_id != train_data.level_id].class_id))


(array([201201, 201202, 201203, 201204, 201205, 201206, 201207, 201208,
       201209, 201210, 201211, 201212, 201301, 201302, 201303, 201304,
       201305, 201306, 201307, 201308, 201309, 201310, 201311, 201312,
       201401, 201402, 201403, 201404, 201405, 201406, 201407, 201408,
       201409, 201410, 201411, 201412, 201501, 201502, 201503, 201504,
       201505, 201506, 201507, 201508, 201509, 201510, 201511, 201512,
       201601, 201602, 201603, 201604, 201605, 201606, 201607, 201608,
       201609, 201610, 201611, 201612, 201701, 201702, 201703, 201704,
       201705, 201706, 201707, 201708, 201709, 201710], dtype=int64), array([171, 153, 168, 156, 166, 159, 176, 172, 187, 183, 184, 183, 213,
       188, 178, 192, 193, 195, 211, 218, 225, 235, 235, 221, 260, 230,
       240, 256, 278, 267, 301, 299, 348, 342, 330, 347,  22,  23,  27,
        22,  21,  18,  21,  26,  24,  25,  24,  28,  30,  31,  29,  22,
        17,  17,  16,  18,  18,  17,  14,  14,  17,  18,  19,  17,  19,
 

In [87]:
train_data.groupby(['class_id','sale_date']).


(array([201201, 201202, 201203, 201204, 201205, 201206, 201207, 201208,
       201209, 201210, 201211, 201212, 201301, 201302, 201303, 201304,
       201305, 201306, 201307, 201308, 201309, 201310, 201311, 201312,
       201401, 201402, 201403, 201404, 201405, 201406, 201407, 201408,
       201409, 201410, 201411, 201412, 201501, 201502, 201503, 201504,
       201505, 201506, 201507, 201508, 201509, 201510, 201511, 201512,
       201601, 201602, 201603, 201604, 201605, 201606, 201607, 201608,
       201609, 201610, 201611, 201612, 201701, 201702, 201703, 201704,
       201705, 201706, 201707, 201708, 201709, 201710], dtype=int64), array([171, 153, 168, 156, 166, 159, 176, 172, 187, 183, 184, 183, 213,
       188, 178, 192, 193, 195, 211, 218, 225, 235, 235, 221, 260, 230,
       240, 256, 278, 267, 301, 299, 348, 342, 330, 347,  22,  23,  27,
        22,  21,  18,  21,  26,  24,  25,  24,  28,  30,  31,  29,  22,
        17,  17,  16,  18,  18,  17,  14,  14,  17,  18,  19,  17,  19,
 

In [ ]:
 

train_data['level_id'].fillna(-1,inplace=True) 
train_data['level_id'].astype(int)
train_data['power'].fillna(75.5,inplace=True)
train_data['power'].astype(float)
train_data['fuel_type_id'].fillna(1,inplace=True)
train_data['fuel_type_id'].astype(int)
for name in ['brand_id', 'price_level','type_id', 'level_id','department_id',\
             'TR', 'gearbox_type', 'price_level','driven_type_id', \
             'newenergy_type_id','emission_standards_id',\
             'cylinder_number','rated_passenger','if_MPV_id',\
             'if_luxurious_id','power','fuel_type_id']:
    print(name,len(np.unique(train_data[name])))


(array([201201, 201202, 201203, 201204, 201205, 201206, 201207, 201208,
       201209, 201210, 201211, 201212, 201301, 201302, 201303, 201304,
       201305, 201306, 201307, 201308, 201309, 201310, 201311, 201312,
       201401, 201402, 201403, 201404, 201405, 201406, 201407, 201408,
       201409, 201410, 201411, 201412, 201501, 201502, 201503, 201504,
       201505, 201506, 201507, 201508, 201509, 201510, 201511, 201512,
       201601, 201602, 201603, 201604, 201605, 201606, 201607, 201608,
       201609, 201610, 201611, 201612, 201701, 201702, 201703, 201704,
       201705, 201706, 201707, 201708, 201709, 201710], dtype=int64), array([171, 153, 168, 156, 166, 159, 176, 172, 187, 183, 184, 183, 213,
       188, 178, 192, 193, 195, 211, 218, 225, 235, 235, 221, 260, 230,
       240, 256, 278, 267, 301, 299, 348, 342, 330, 347,  22,  23,  27,
        22,  21,  18,  21,  26,  24,  25,  24,  28,  30,  31,  29,  22,
        17,  17,  16,  18,  18,  17,  14,  14,  17,  18,  19,  17,  19,
 

In [41]:
train_data['level_id']

6190     3.0
8766     3.0
13743    3.0
5465     3.0
6470     3.0
7399     3.0
12112    3.0
14425    3.0
15196    3.0
7097     3.0
7487     3.0
10163    3.0
10605    3.0
13333    3.0
13820    3.0
6797     3.0
7032     3.0
9738     3.0
12513    3.0
15250    3.0
16795    3.0
17085    3.0
5425     3.0
5879     3.0
9515     3.0
10634    3.0
15371    3.0
17083    3.0
10187    3.0
11296    3.0
        ... 
1432     1.0
1740     1.0
2065     1.0
3089     1.0
2127     1.0
2627     1.0
2785     1.0
3391     1.0
2452     1.0
3238     1.0
3908     1.0
3928     1.0
2995     1.0
3386     1.0
3474     1.0
3700     1.0
2080     1.0
2692     1.0
3914     1.0
4635     1.0
2927     1.0
3014     1.0
3446     1.0
4656     1.0
3745     1.0
4626     1.0
4854     1.0
4855     1.0
3876     1.0
4390     1.0
Name: level_id, Length: 20157, dtype: float64